version: '3.8'

services:
  api:
    build: ./python-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./code_reviews.db
      - APP_ENV=development
      - LOG_LEVEL=INFO
    volumes:
      - ./python-service:/app
      - db-data:/app/data
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

---
